# Generated by Django 5.2 on 2025-04-17 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialcustomer',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='potentialcustomer',
            name='potential_customer_status',
            field=models.CharField(choices=[('Not Contacted', 'Not Contacted'), ('Emailed', 'Emailed'), ('Contacted', 'Contacted')], default='Not Contacted', max_length=20),
        ),
    ]
