# Generated by Django 5.2 on 2025-04-17 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_potentialcustomer_assigned_agent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialcustomer',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='potentialcustomer',
            name='potential_customer_status',
            field=models.CharField(choices=[('not_contacted', 'Not Contacted'), ('emailed', 'Emailed'), ('contacted', 'Contacted')], default='not_contacted', max_length=20),
        ),
    ]
