# Generated by Django 5.2 on 2025-04-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_potentialcustomer_assigned_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialcustomer',
            name='potential_customer_is_dead',
            field=models.BooleanField(default=False),
        ),
    ]
