# Generated by Django 5.2 on 2025-04-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_externalemaillog_ticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='case_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.CharField(default='admin', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='originating_department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='problem_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
