# Generated by Django 5.2 on 2025-04-19 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_ticket_action_plan_ticket_case_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('phone_type', models.CharField(choices=[('Business', 'Business'), ('Home', 'Home'), ('Other', 'Other')], max_length=50)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callers', to='dashboard.ticket')),
            ],
        ),
    ]
