# Generated by Django 5.2 on 2025-04-19 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0010_remove_ticket_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='current_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_tickets', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='originating_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_tickets', to='auth.group'),
        ),
    ]
