# Generated by Django 5.2 on 2025-04-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_ticket_current_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_id',
        ),
    ]
