# Generated by Django 5.2 on 2025-04-19 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_ticket_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dashboard.ticketcomment'),
        ),
    ]
