# Generated by Django 5.2 on 2025-04-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_pipeline_pipelinestage_leadpipelineentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadpipelineentry',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
