# Generated by Django 5.2 on 2025-04-22 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_leadpipelineentry_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadpipelineentry',
            name='done_in_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='done_leads', to='dashboard.pipelinestage'),
        ),
    ]
