# Generated by Django 5.2 on 2025-04-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_leadpipelineentry_done_in_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadpipelineentry',
            name='done_in_stage',
        ),
        migrations.AddField(
            model_name='leadpipelineentry',
            name='done_stages',
            field=models.ManyToManyField(blank=True, related_name='completed_entries', to='dashboard.pipelinestage'),
        ),
    ]
