# Generated by Django 5.2 on 2025-04-22 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_leadpipelineentry_done_in_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadpipelineentry',
            name='entered_stage_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
