# Generated by Django 5.2 on 2025-04-22 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0019_leadpipelineentry_entered_stage_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, help_text='When the meeting ends', null=True)),
                ('agenda', models.TextField(blank=True, help_text='Pre‑meeting notes or agenda')),
                ('summary', models.TextField(blank=True, help_text='Post‑meeting summary (fill after)')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_created', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(help_text='Departments whose users you can invite', related_name='meetings', to='auth.group')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', "Don't know")], default='maybe', max_length=5)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When they last updated their RSVP', null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'unique_together': {('meeting', 'user')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meetings', through='dashboard.MeetingParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
