# Generated by Django 5.2 on 2025-04-23 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_meetingparticipant_reminder_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='(For Agents) pick one existing customer/lead to invite', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(blank=True, help_text='Pre-meeting notes or agenda'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='summary',
            field=models.TextField(blank=True, help_text='Post-meeting summary (fill after)'),
        ),
    ]
