# Generated by Django 5.2 on 2025-04-23 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_meeting_customer_alter_meeting_agenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_as_lead', to='dashboard.potentialcustomer'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='dashboard.customer'),
        ),
    ]
